[CONFIG]
tdg_interval = [20109, 20861]
defense_range = [20338,20538]
points = 201
min_def = 46
nb_drapo = 0
day = 34
iterations = 30000
is_reactor_built = false

[ESTIMATION25]
enabled = true
iterations = 1000000
observations = ["24:17188-17674"]
