#!/usr/bin/env pwsh
#MISE description="Run DebordoStat for Windows"
#MISE depends=["win:check-prerequisites"]

$ErrorActionPreference = "Stop"

Write-Host "Running DebordoStat for Windows"
cargo run --release
exit 0
#!/usr/bin/env pwsh
#MISE description="✅ Check prerequisites for Rust"
#MISE hide=true

$ErrorActionPreference = "Stop"

if (-not (Get-Command cargo -ErrorAction SilentlyContinue)) {
    Write-Host "❌ Rust is not installed"
    exit 1
}

